name: Publish Node.js container image based on Ubuntu

on:
  schedule:
    - cron: '0 17 * * 2'
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/node

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
        ubuntu: [impish]
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{env.REGISTRY}}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          tags: |
            type=raw,${{matrix.node}}-${{matrix.ubuntu}}
          labels: |
            org.opencontainers.image.title=Node.js ${{matrix.node}} container image based on Ubuntu ${{matrix.ubuntu}}
            org.opencontainers.image.description=Node.js ${{matrix.node}} container image based on Ubuntu ${{matrix.ubuntu}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: node/${{matrix.node}}/${{matrix.ubuntu}}
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le, linux/s390x
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
